services:
  elize:
    image: w3clouds-elize:v1.0
    container_name: elize
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - dockge_default
    volumes:
      - ./.env:/app/.env:ro,Z
      - ./characters:/app/characters:ro,Z
networks:
  dockge_default:
    external: true
